Fix automatic Terraform deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,11 +35,18 @@ jobs:
         run: terraform validate -no-color
 
       - name: Terraform Plan
-        run: terraform plan -no-color -input=false -out=tfplan
+        id: plan
+        run: terraform plan -no-color -input=false -out=tfplan -detailed-exitcode
+        continue-on-error: true # Allow exit code 2 (meaning changes exist) to continue.
+
+      - name: Check Terraform plan status
+        # If the plan failed with a real error (exit code 1), fail the pipeline.
+        if: steps.plan.outputs.exitcode == '1'
+        run: exit 1
 
       - name: Terraform Apply
-        run: terraform apply -auto-approve tfplan
-        if: ${{ github.ref_name == github.event.repository.default_branch }}
+        if: steps.plan.outputs.exitcode == '2' && ${{ github.ref_name == github.event.repository.default_branch }}
+        run: terraform apply -input=false tfplan
 
   ansible:
     name: Configure with Ansible
